### ISSUE TITLE
JOSE review - plain text LICENSE file

### ISSUE THREAD

**Issue by tomsing1** [TrevorFrench/R-for-Data-Analysis#10]
Hi! 

Great course / e-book!
I am one of the reviewers of your submission to the Journal of Open Source Education. As I am going through their checklist, I will create issues here that you might want to take a look at. 

For example, JOSE asks me to verify:

> **License:** Does the repository contain a plain-text LICENSE file with the contents of a standard license? (OSI-approved for code, Creative Commons for content)

You are already [linking to the CC license](https://trevorfrench.github.io/R-for-Data-Analysis/#license). Would you mind adding the LICENSE text to the repository as well?

**Comment by TrevorFrench** [comment]
Hi- thanks for agreeing to review!

I added the LICENSE file to this repository. If that looks alright to you, I'll close this issue.
