### ISSUE TITLE
JOSE review - paper.md is missing the affiliations field

### ISSUE THREAD

**Issue by tomsing1** [TrevorFrench/R-for-Data-Analysis#11]
It seems that the JOSE bot cannot create the PDF version of the `paper.md` file because the `affiliations` field is missing the YAML header (see [here](https://github.com/openjournals/jose-reviews/issues/202#issuecomment-1468493764)). Would you mind adding it?

[Here is an example](https://raw.githubusercontent.com/Edinburgh-Chemistry-Teaching/Data-driven-chemistry/main/paper/paper.md) of another manuscript (currently under review) that includes several affiliations.

**Comment by TrevorFrench** [comment]
I updated the `paper.md` file to include affiliations (thanks for sharing an example); however, I am not affiliated with any organization. I listed my affiliation as "Independent". Do you think that is sufficient?

**Comment by tomsing1** [comment]
@TrevorFrench I just saw that [the JOSS documentation](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) contains an example for independent researchers like yourself. It suggests `Independent Researcher`, `Country`.  Perhaps that works for you, too?

**Comment by TrevorFrench** [comment]
@tomsing1 Oh, perfect! I just updated it to be "Independent Researcher, USA" in PR #13
