### ISSUE TITLE
JOSE review: story of the authors

### ISSUE THREAD

**Issue by tomsing1** [TrevorFrench/R-for-Data-Analysis#18]
The JOSE review guidelines ask:
>  Does the paper tell the "story" of how the authors came to develop it, or what their expertise is?

Maybe you want to include a chapter introducing your story, background and expertise?

**Comment by TrevorFrench** [comment]
@tomsing1 should this go in the content or in the paper?

**Comment by tomsing1** [comment]
I was thinking adding short "About me" section of your content would be nice.

**Comment by TrevorFrench** [comment]
@tomsing1 I added an "About Me" section to the README as well as the introduction in PR #21

**Comment by tomsing1** [comment]
Awesome! Thank you for adding it - really interesting to read about your journey.
