### ISSUE TITLE
JOSE: additional references / comparisons with existing online materials

### ISSUE THREAD

**Issue by tomsing1** [TrevorFrench/R-for-Data-Analysis#19]
It would be great if you could include a few more references to / a comparison with existing educational materials in the paper. 
For example, Software Carpentry has a long-standing section on [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/). How does your book compare, e.g. where are differences in scope, what are gaps you are filling?

**Comment by TrevorFrench** [comment]
I agree this wasn't adequately addressed in the paper. I made an adjustment in PR #20. Here is the updated [statement of need](https://github.com/TrevorFrench/R-for-Data-Analysis/blob/main/paper/paper.md). Let me know if you think that is sufficient.

**Comment by tomsing1** [comment]
Thank you for taking care of this!
